//// Generated by the protocol buffer compiler.  DO NOT EDIT!
//// source: t_y_trace_pbf.proto
//
//// This CPP symbol can be defined to use imports that match up to the framework
//// imports needed when using CocoaPods.
//#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
// #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
//#endif
//
//#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
// #import <Protobuf/GPBProtocolBuffers.h>
//#else
// #import "GPBProtocolBuffers.h"
//#endif
//
//#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
//#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
//#endif
//#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
//#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
//#endif
//
//// @@protoc_insertion_point(imports)
//
//#pragma clang diagnostic push
//#pragma clang diagnostic ignored "-Wdeprecated-declarations"
//
//CF_EXTERN_C_BEGIN
//
//@class TYTracePointPbf;
//
//NS_ASSUME_NONNULL_BEGIN
//
//#pragma mark - TYTracePbfRoot
//
///**
// * Exposes the extension registry for this file.
// *
// * The base class provides:
// * @code
// *   + (GPBExtensionRegistry *)extensionRegistry;
// * @endcode
// * which is a @c GPBExtensionRegistry that includes all the extensions defined by
// * this file and all files that it depends on.
// **/
//@interface TYTracePbfRoot : GPBRootObject
//@end
//
//#pragma mark - TYTracePointPbf
//
//typedef GPB_ENUM(TYTracePointPbf_FieldNumber) {
//  TYTracePointPbf_FieldNumber_Index = 1,
//  TYTracePointPbf_FieldNumber_X = 2,
//  TYTracePointPbf_FieldNumber_Y = 3,
//  TYTracePointPbf_FieldNumber_Floor = 4,
//  TYTracePointPbf_FieldNumber_Timestamp = 5,
//};
//
//@interface TYTracePointPbf : GPBMessage
//
//@property(nonatomic, readwrite) uint32_t index;
//
//@property(nonatomic, readwrite) BOOL hasIndex;
//@property(nonatomic, readwrite) double x;
//
//@property(nonatomic, readwrite) BOOL hasX;
//@property(nonatomic, readwrite) double y;
//
//@property(nonatomic, readwrite) BOOL hasY;
//@property(nonatomic, readwrite) uint32_t floor;
//
//@property(nonatomic, readwrite) BOOL hasFloor;
//@property(nonatomic, readwrite) double timestamp;
//
//@property(nonatomic, readwrite) BOOL hasTimestamp;
//@end
//
//#pragma mark - TYTracePbf
//
//typedef GPB_ENUM(TYTracePbf_FieldNumber) {
//  TYTracePbf_FieldNumber_TraceId = 1,
//  TYTracePbf_FieldNumber_Timestamp = 2,
//  TYTracePbf_FieldNumber_PointsArray = 3,
//};
//
//@interface TYTracePbf : GPBMessage
//
//@property(nonatomic, readwrite, copy, null_resettable) NSString *traceId;
///** Test to see if @c traceId has been set. */
//@property(nonatomic, readwrite) BOOL hasTraceId;
//
//@property(nonatomic, readwrite) double timestamp;
//
//@property(nonatomic, readwrite) BOOL hasTimestamp;
//@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TYTracePointPbf*> *pointsArray;
///** The number of items in @c pointsArray without causing the array to be created. */
//@property(nonatomic, readonly) NSUInteger pointsArray_Count;
//
//@end
//
//NS_ASSUME_NONNULL_END
//
//CF_EXTERN_C_END
//
//#pragma clang diagnostic pop
//
//// @@protoc_insertion_point(global_scope)
