// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: t_y_raw_data_collection_pbf.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class TYRawBeaconSignalPbf;
@class TYRawHeadingEventPbf;
@class TYRawLocationPbf;
@class TYRawSignalEventPbf;
@class TYRawStepEventPbf;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - TYRawDataCollectionPbfRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface TYRawDataCollectionPbfRoot : GPBRootObject
@end

#pragma mark - TYRawStepEventPbf

typedef GPB_ENUM(TYRawStepEventPbf_FieldNumber) {
  TYRawStepEventPbf_FieldNumber_Timestamp = 1,
};

@interface TYRawStepEventPbf : GPBMessage

@property(nonatomic, readwrite) double timestamp;

@property(nonatomic, readwrite) BOOL hasTimestamp;
@end

#pragma mark - TYRawHeadingEventPbf

typedef GPB_ENUM(TYRawHeadingEventPbf_FieldNumber) {
  TYRawHeadingEventPbf_FieldNumber_Timestamp = 1,
  TYRawHeadingEventPbf_FieldNumber_Heading = 2,
};

@interface TYRawHeadingEventPbf : GPBMessage

@property(nonatomic, readwrite) double timestamp;

@property(nonatomic, readwrite) BOOL hasTimestamp;
@property(nonatomic, readwrite) double heading;

@property(nonatomic, readwrite) BOOL hasHeading;
@end

#pragma mark - TYRawBeaconSignalPbf

typedef GPB_ENUM(TYRawBeaconSignalPbf_FieldNumber) {
  TYRawBeaconSignalPbf_FieldNumber_Uuid = 1,
  TYRawBeaconSignalPbf_FieldNumber_Major = 2,
  TYRawBeaconSignalPbf_FieldNumber_Minor = 3,
  TYRawBeaconSignalPbf_FieldNumber_X = 4,
  TYRawBeaconSignalPbf_FieldNumber_Y = 5,
  TYRawBeaconSignalPbf_FieldNumber_Floor = 6,
  TYRawBeaconSignalPbf_FieldNumber_Rssi = 7,
  TYRawBeaconSignalPbf_FieldNumber_Accuracy = 8,
};

@interface TYRawBeaconSignalPbf : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *uuid;
/** Test to see if @c uuid has been set. */
@property(nonatomic, readwrite) BOOL hasUuid;

@property(nonatomic, readwrite) uint32_t major;

@property(nonatomic, readwrite) BOOL hasMajor;
@property(nonatomic, readwrite) uint32_t minor;

@property(nonatomic, readwrite) BOOL hasMinor;
@property(nonatomic, readwrite) double x;

@property(nonatomic, readwrite) BOOL hasX;
@property(nonatomic, readwrite) double y;

@property(nonatomic, readwrite) BOOL hasY;
@property(nonatomic, readwrite) uint32_t floor;

@property(nonatomic, readwrite) BOOL hasFloor;
@property(nonatomic, readwrite) uint32_t rssi;

@property(nonatomic, readwrite) BOOL hasRssi;
@property(nonatomic, readwrite) double accuracy;

@property(nonatomic, readwrite) BOOL hasAccuracy;
@end

#pragma mark - TYRawLocationPbf

typedef GPB_ENUM(TYRawLocationPbf_FieldNumber) {
  TYRawLocationPbf_FieldNumber_X = 1,
  TYRawLocationPbf_FieldNumber_Y = 2,
  TYRawLocationPbf_FieldNumber_Floor = 3,
};

@interface TYRawLocationPbf : GPBMessage

@property(nonatomic, readwrite) double x;

@property(nonatomic, readwrite) BOOL hasX;
@property(nonatomic, readwrite) double y;

@property(nonatomic, readwrite) BOOL hasY;
@property(nonatomic, readwrite) uint32_t floor;

@property(nonatomic, readwrite) BOOL hasFloor;
@end

#pragma mark - TYRawSignalEventPbf

typedef GPB_ENUM(TYRawSignalEventPbf_FieldNumber) {
  TYRawSignalEventPbf_FieldNumber_Timestamp = 1,
  TYRawSignalEventPbf_FieldNumber_BeaconsArray = 2,
  TYRawSignalEventPbf_FieldNumber_Location = 3,
  TYRawSignalEventPbf_FieldNumber_ImmediateLocation = 4,
};

@interface TYRawSignalEventPbf : GPBMessage

@property(nonatomic, readwrite) double timestamp;

@property(nonatomic, readwrite) BOOL hasTimestamp;
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TYRawBeaconSignalPbf*> *beaconsArray;
/** The number of items in @c beaconsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger beaconsArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) TYRawLocationPbf *location;
/** Test to see if @c location has been set. */
@property(nonatomic, readwrite) BOOL hasLocation;

@property(nonatomic, readwrite, strong, null_resettable) TYRawLocationPbf *immediateLocation;
/** Test to see if @c immediateLocation has been set. */
@property(nonatomic, readwrite) BOOL hasImmediateLocation;

@end

#pragma mark - TYRawDataCollectionPbf

typedef GPB_ENUM(TYRawDataCollectionPbf_FieldNumber) {
  TYRawDataCollectionPbf_FieldNumber_DataId = 1,
  TYRawDataCollectionPbf_FieldNumber_Timestamp = 2,
  TYRawDataCollectionPbf_FieldNumber_StepEventsArray = 3,
  TYRawDataCollectionPbf_FieldNumber_HeadingEventsArray = 4,
  TYRawDataCollectionPbf_FieldNumber_SignalEventsArray = 5,
};

@interface TYRawDataCollectionPbf : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *dataId;
/** Test to see if @c dataId has been set. */
@property(nonatomic, readwrite) BOOL hasDataId;

@property(nonatomic, readwrite) double timestamp;

@property(nonatomic, readwrite) BOOL hasTimestamp;
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TYRawStepEventPbf*> *stepEventsArray;
/** The number of items in @c stepEventsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger stepEventsArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TYRawHeadingEventPbf*> *headingEventsArray;
/** The number of items in @c headingEventsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger headingEventsArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TYRawSignalEventPbf*> *signalEventsArray;
/** The number of items in @c signalEventsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger signalEventsArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
